### ISSUE TITLE
在中国无法播放

### ISSUE THREAD

**Issue by 2005jick** [ajzbc/youtube-extractor#2]
能否设置一下播放问题？现在播放是调用video.google.com，但是在中国不能访问，是否可以避开？采用反代的方法？

**Comment by ajzbc** [comment]
I'm a little confused what you are saying. Google translate may be wrong but you are saying to try to find a url that isn't blocked in China?

**Comment by dora-admin001** [comment]
I thinks it means he cannot extract video due to china policy (GFW) blocked video.google.com
