### ISSUE TITLE
This is marvelous

### ISSUE THREAD

**Issue by copypasteho** [ajzbc/youtube-extractor#3]
Just wanted to drop by here and state how marvelous this is -- especially considering that you managed to pull this off using Web Workers. Considering that you're hosting this, what do you think the overhead is since the free tier is limited. Or am I looking at this the wrong way?

Anyway, wow. NOICE

**Comment by ajzbc** [comment]
Since it is just getting the url for videos and not downloading them it is very easy to run. It just pay per request.
